### ISSUE TITLE
Tooltip Error

### ISSUE THREAD

**Issue by YanYas** [vvvv/VL.OpenCV#34]
Float64 Images fail to get converted correctly before being previewed:

> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 6 (CV_64F)

   at OpenCV.Filter.ConvertColor.<Update>c__DisplayClass37779189.<Update>b__0(InputArray Arg 1, OutputArray Arg 2) in C:\Users\H\Documents\vvvv\beta-preview\Packages\VL.OpenCV.0.2.106-alpha\VL.OpenCV.vl:line 183723
   at OpenCV.Filter.Filter__1M_1_.Update(Boolean Apply, Action`2 Operation, CvImage Input, CvImage& Output) in C:\Users\H\Documents\vvvv\beta-preview\Packages\VL.OpenCV.0.2.106-alpha\VL.OpenCV.vl:line 188290

Cheers

**Comment by YanYas** [comment]
Suggested Fix:
In OpenCV 'ToImage'
![VL OpenCV-ToImage_2019 08 03-15 22 38](https://user-images.githubusercontent.com/9497052/62413047-97886900-b602-11e9-9b4d-f09648d59b35.png)

**Comment by ravazquez** [comment]
Suggested fix only applies to 3-channel images, would not cover many cases still. I will look into this.
